name: 'Issue Assistant'
description: 'AI-powered GitHub Issue assistant that analyzes issues and provides intelligent responses using GPT-4 or Claude'
author: 'workflowkit'

# Categories for GitHub Marketplace
categories:
  - 'AI'
  - 'Code Review'
  - 'Issue Management'

branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  github_token:
    description: 'GitHub token with repo scope'
    required: true
  ai_type:
    description: 'AI model type (openai/claude)'
    required: true
    default: 'openai'
  openai_api_key:
    description: 'OpenAI API Key (required if ai_type is openai)'
    required: false
  claude_api_key:
    description: 'Anthropic Claude API Key (required if ai_type is claude)'
    required: false
  enable_comment:
    description: 'Enable AI-powered code analysis comments on issues'
    required: false
    default: 'false' # Default is false, but you must enable if you want to use this action
  enable_label:
    description: 'Enable AI-powered label suggestions for issues'
    required: false
    default: 'false' # Default is false, but you must enable if you want to use this action

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    AI_TYPE: ${{ inputs.ai_type }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    CLAUDE_API_KEY: ${{ inputs.claude_api_key }}
    ENABLE_COMMENT: ${{ inputs.enable_comment }}
    ENABLE_LABEL: ${{ inputs.enable_label }}
    TARGET_REPO_OWNER: ${{ github.repository_owner }}
    TARGET_REPO_NAME: ${{ github.event.repository.name }}
    GITHUB_EVENT_PATH: ${{ github.event_path }} 