name: 'Issue Assistant'
description: 'AI-powered GitHub Issue assistant that provides intelligent responses based on repository content'
branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token with repo scope'
    required: true
  ai_type:
    description: 'AI model type (openai/claude)'
    required: true
    default: 'openai'
  openai_api_key:
    description: 'OpenAI API Key (required if ai_type is openai)'
    required: false
  claude_api_key:
    description: 'Anthropic Claude API Key (required if ai_type is claude)'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    AI_TYPE: ${{ inputs.ai_type }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    CLAUDE_API_KEY: ${{ inputs.claude_api_key }}
    TARGET_REPO_OWNER: ${{ github.repository_owner }}
    TARGET_REPO_NAME: ${{ github.event.repository.name }}
    GITHUB_EVENT_PATH: ${{ github.event_path }} 